package cobranza.v2.pgt.com.models.enums;

import java.util.Arrays;

public enum DocumentoSector{
    FACTURA_COMPRA_VENTA(1, "FACTURA COMPRA VENTA"),
    RECIBO_ALQUILER_BIEN_INMUEBLE(2, "FACTURA DE ALQUILER DE BIENES INMUEBLES"),
    FACTURA_COMERCIAL_EXPORTACION(3, "FACTURA COMERCIAL DE EXPORTACION"),
    FACTURA_LIBRE_CONSIGNACION(4, "FACTURA COMERCIAL DE EXPORTACION EN LIBRE CONSIGNACION"),
    FACTURA_ZONA_FRANCA(5, "FACTURA DE ZONA FRANCA"),
    FACTURA_SERVICIO_TURISTICO_HOSPEDAJE(6, "FACTURA DE SERVICIOS TURISTICOS Y HOSPEDAJE"),
    FACTURA_SEGURIDAD_ALIMENTARIA(7, "FACTURA SEGURIDAD ALIMENTARIA Y ABASTECIMIENTO"),
    FACTURA_TASA_CERO(8, "FACTURA TASA CERO"),
    FACTURA_COMPRA_VENTA_MONEDA_EXTRANJERA(9, "FACTURA DE COMPRA VENTA MONEDA EXTRANJERA"),
    FACTURA_DUTTY_FREE(10, "FACTURA DUTTY FREE"),
    FACTURA_SECTOR_EDUCATIVO(11,"FACTURA SECTOR EDUCATIVO"),
    FACTURA_COMERCIALIZACION_HIDROCARBURO(12, "FACTURA COMERCIALIZACION HIDROCARBUROS"),
    FACTURA_SERVICIO_BASICO(13, "FACTURA SERVICIOS BASICOS"),
    FACTURA_ALCANZADA_ICE(14, "FACTURA ALCANZADA POR ICE"),
    FACTURA_ENTIDAD_FINANCIERA(15, "FACTURA ENTIDAD FINANCIERA"),
    FACTURA_HOTEL(16, "FACTURA HOTELES"),
    FACTURA_HOSPITAL_CLINICA(17, "FACTURA HOSPITALES CLINICAS"),
    FACTURA_JUEGO_AZAR(18, "FACTURA JUEGO DE AZAR"),
    FACTURA_HIDROCARBURO(19, "FACTURA DE HIDROCARBUROS"),
    FACTURA_COMERCIAL_EXPORTACION_MINERA(20, "FACTURA COMERCIAL DE EXPORTACION DE MINERALES"),
    FACTURA_VENTA_MINERAL(21, "FACTURA VENTA INTERNA DE MINERALES"),
    FACTURA_TELECOMUNICACION(22, "FACTURA TELECOMUNICACIONES"),
    FACTURA_PREVALORADA(23,	"FACTURA PREVALORADA"),
    NOTA_CREDITO_DEBITO(24,	"NOTA CREDITO DEBITO"),
    FACTURA_COMERCIAL_EXPORTACION_SERVICIOS(28,	"FACTURA COMERCIAL DE EXPORTACION DE SERVICIOS"),
    NOTA_CONCILIACION(29,	"NOTA DE CONCILIACION"),
    BOLETO_AEREO(30,	"BOLETO AEREO"),
    FACTURA_SUMINISTRO_ENERGIA(31,	"FACTURA DE SUMINISTRO DE ENERGIA"),
    FACTURA_ALCANZADA_ICE_ZF(32,	"FACTURA ALCANZADA POR ICE - ZONA FRANCA");

    private final int codigo;
    private final String descripcion;

    DocumentoSector(int codigo, String descripcion) {

        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public String getDescripcion(){ return descripcion;}

    public static DocumentoSector getEnumFromCode(Integer pCodigo) {
        return Arrays.stream(DocumentoSector.values()).filter(e -> pCodigo.equals(e.codigo)).findFirst().get();
    }
}
