
package cobranza.v2.pgt.com.utils.otros;

import lombok.Data;

@Data
public class Order {
  
  public Long id;
  public String admin_graphql_api_id;
  public int app_id;
  public String browser_ip;
  public boolean buyer_accepts_marketing;
  public Object cancel_reason;
  public Object cancelled_at;
  public String cart_token;
  public Object checkout_id;
  public String checkout_token;
  // public ClientDetails client_details;
  // public Date closed_at;
  public boolean confirmed;
  public String contact_email;
  // public Date created_at;
  public String currency;
  public String current_subtotal_price;
  // public CurrentSubtotalPriceSet current_subtotal_price_set;
  public String current_total_discounts;
  // public CurrentTotalDiscountsSet current_total_discounts_set;
  public Object current_total_duties_set;
  public String current_total_price;
  // public CurrentTotalPriceSet current_total_price_set;
  public String current_total_tax;
  // public CurrentTotalTaxSet current_total_tax_set;
  public String customer_locale;
  public Object device_id;
  // public ArrayList<Object> discount_codes;
  public String email;
  public boolean estimated_taxes;
  public String financial_status;
  public String fulfillment_status;
  public String gateway;
  public String landing_site;
  public Object landing_site_ref;
  public Object location_id;
  public String name;
  public String note;
  // public ArrayList<NoteAttribute> note_attributes;
  public int number;
  public int order_number;
  public String order_status_url;
  public Object original_total_duties_set;
  // public ArrayList<String> payment_gateway_names;
  public String phone;
  public String presentment_currency;
  // public Date processed_at;
  public String processing_method;
  public Object reference;
  public String referring_site;
  public Object source_identifier;
  public String source_name;
  public Object source_url;
  public String subtotal_price;
  // public SubtotalPriceSet subtotal_price_set;
  public String tags;
  // public ArrayList<TaxLine> tax_lines;
  public boolean taxes_included;
  public boolean test;
  public String token;
  public String total_discounts;
  // public TotalDiscountsSet total_discounts_set;
  public String total_line_items_price;
  // public TotalLineItemsPriceSet total_line_items_price_set;
  public String total_outstanding;
  public String total_price;
  // public TotalPriceSet total_price_set;
  public String total_price_usd;
  // public TotalShippingPriceSet total_shipping_price_set;
  public String total_tax;
  // public TotalTaxSet total_tax_set;
  public String total_tip_received;
  public int total_weight;
  // public Date updated_at;
  public Object user_id;
  // public BillingAddress billing_address;
  // public Customer customer;
  // public ArrayList<DiscountApplication> discount_applications;
  // public ArrayList<Fulfillment> fulfillments;
  // public ArrayList<LineItem> line_items;
  public Object payment_terms;
  // public ArrayList<Object> refunds;
  // public ShippingAddress shipping_address;
  // public ArrayList<ShippingLine> shipping_lines;
}
